### ISSUE TITLE
Wrong test data

### ISSUE THREAD

**Issue by marcus1337** [DatabaseGroup/tree-similarity#11]
In the test data file located [here](https://github.com/DatabaseGroup/tree-similarity/blob/develop/test/ted/ted_test_data.txt) I noted that the last test contains invalid input. This would cause the test to always fail, which is probably something that you, the developers, do not want. The error can be easily found by opening up "CTRL+F" and searching "{{". "{{" is invalid syntax. The test is currently commented with, "# Bolzano - large trees (causing int overflow in strategy computation)".

**Comment by mateuszpawlik** [comment]
The input is valid. It represents an empty label. The details on the input format can be found in `src/parser/bracket_notation_parser.h`. I copy it here:
```
/// {LABEL{LABEL}{LABEL}}
///
/// where LABEL allows any character BUT the the structure brackets (by default
/// the curly brackets: {}) must be escaped as follows: \{ \}.
///
/// Example input with complex labels:
/// {a{\{[b],\{key:"value"\}\}{}}}
/// which is a path of three nodes with labels as follows:
///
///                         target LABEL (after removing escapes):
/// a                       -> a
/// |
/// \{[b],\{key:"value"\}\} -> {[b],{key:"value"}}
/// |
/// ""                      -> an empty label
```

**Comment by marcus1337** [comment]
ah, ok.
