### ISSUE TITLE
Add a link to the website

### ISSUE THREAD

**Issue by thuetter** [DatabaseGroup/tree-similarity#15]
Refer to additional information on the website http://tree-edit-distance.dbresearch.uni-salzburg.at.

**Comment by FHantke** [comment]
It may fit in this issue: The repository links on your website are not working anymore (e.g. https://github.com/DatabaseGroup/tree-similarity/tree/develop).

**Comment by thuetter** [comment]
Thank you for the hint. I updated the links accordingly. May I ask you to retry and let me know?

**Comment by FHantke** [comment]
Works fine, links are up to date :+1:

**Comment by thuetter** [comment]
Thank you!
