### ISSUE TITLE
Introduce CI for code building

### ISSUE THREAD

**Issue by mateuszpawlik** [DatabaseGroup/tree-similarity#17]
We should finally build the code automatically. I propose GitHub Actions with the 2,000 minutes/month. It should be enough for building.

**Comment by mateuszpawlik** [comment]
@thuetter, the CI takes now 4m20s. Is that ok, or should we make it faster?

**Comment by thuetter** [comment]
@mateuszpawlik We could exclude the time-intensive tests, namely:
```
Test  #9: ted_join_correctness_test_naivejoin_129 ........................   Passed   22.41 sec
Test #15: ted_join_correctness_test_guhajoin_129 .........................   Passed   28.21 sec
Test #71: ted_correctness_test_touzet_depth_pruning ......................   Passed   18.12 sec
```
Out of a total of 120s on my local machine.

**Comment by mateuszpawlik** [comment]
Yes, lets do that. On GitHub it takes even longer:
```
Test  #9: ted_join_correctness_test_naivejoin_129 ........................   Passed   17.93 sec
Test #15: ted_join_correctness_test_guhajoin_129 .........................   Passed   95.76 sec
Test #71: ted_correctness_test_touzet_depth_pruning ......................   Passed   50.87 sec
```
There's a [CTestCustom.cmake](../blob/master/test/CTestCustom.cmake) file that lists tests to ignore but I don't remember how does it work. It's used in [CMakeLists.txt](../blob/master/test/CMakeLists.txt). Maybe there's something wrong there.

**Comment by thuetter** [comment]
The build is fast anyways.
