### ISSUE TITLE
Add a `LICENSE` file

### ISSUE THREAD

**Issue by mateuszpawlik** [DatabaseGroup/tree-similarity#18]
I think we should add the `LICENSE` file such that it is automatically recognized but I don't know how GitHub deals with it.

**Comment by thuetter** [comment]
Added an MIT LICENSE file.

**Comment by thuetter** [comment]
Directly committed the file to the master branch. Please verify and close the issue.

**Comment by mateuszpawlik** [comment]
Seems to work. I'm closing this issue.
