### ISSUE TITLE
Need basic usage example

### ISSUE THREAD

**Issue by remz1337** [DatabaseGroup/tree-similarity#22]
I have successfully built the library, and all tests passed. However, I am unable to execute TED, no matter the arguments passed.

Would it be possible to have a very simple example of command line usage?

For example, I tried 

```
./ted {x{a}} {x{b}} -t lgm
./ted '{x{a}}' '{x{b}}' -t lgm
./ted -t lgm '{x{a}}' '{x{b}}'
./ted -t lgm {x{a}} {x{b}}
```

And I always get the same error:
`Incorrect format of source tree. Is the number of opening and closing brackets equal?`

**Comment by remz1337** [comment]
Hmm it was only a quick change I did on my test environment. It uses the cxxopts library (available in vcpkg) to handle command line arguments, so that means anyone that wants to test your program would need to have cxxopts installed on their machine or we need to add vcpkg as a submodule.

If you are willing to support this, then sure I will open a PR with my other branch :)

**Comment by mateuszpawlik** [comment]
Thanks, I will give it a thought. @thuetter, what's your take on it?

**Comment by mateuszpawlik** [comment]
I've found a comparison of different [Command Line Argument Parsing Libraries](https://hackingcpp.com/cpp/libs/cmdline_args_parsing.html) if it helps.
